// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"simple_auth/internal/biz"
	"simple_auth/internal/conf"
	"simple_auth/internal/data"
	"simple_auth/internal/server"
	"simple_auth/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	userRepo := data.NewUserRepo(bootstrap)
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	sessionRepo := data.NewSessionRepo(dataData)
	loginFailureRepo := data.NewLoginFailureRepo(dataData)
	auditRepo := data.NewAuditRepo(bootstrap)
	authorizationUsecase, err := biz.NewAuthorizationUsecase(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authUsecase := biz.NewAuthUsecase(userRepo, sessionRepo, loginFailureRepo, auditRepo, authorizationUsecase, bootstrap, logger)
	readinessRepo := data.NewReadinessRepo(dataData)
	authService, err := service.NewAuthService(authUsecase, readinessRepo, bootstrap, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpServer := server.NewHTTPServer(bootstrap, authService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
